#!/bin/bash

###############################################################################
# Portable PHP Development Server Setup
# For Fisherfolk Management System
# Works with external WAMP MySQL database
###############################################################################

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  Fisherfolk Dashboard - Development Server Setup             ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check for PHP
echo -n "Checking for PHP... "
if ! command -v php &> /dev/null; then
    echo -e "${RED}✗ Not found${NC}"
    echo ""
    echo "PHP is required to run the development server."
    echo ""
    echo "Installation options:"
    echo ""
    echo "1. Ubuntu/Debian:"
    echo "   ${BLUE}sudo apt update${NC}"
    echo "   ${BLUE}sudo apt install php php-mysql php-cli${NC}"
    echo ""
    echo "2. Use WAMP's PHP (Windows/WSL):"
    echo "   Add WAMP's PHP to your PATH"
    echo "   Example: export PATH=\"/mnt/c/wamp64/bin/php/php8.x:\$PATH\""
    echo ""
    echo "3. Download portable PHP:"
    echo "   Visit: https://www.php.net/downloads"
    echo ""
    read -p "Would you like to try installing PHP now? (Ubuntu/Debian only) [y/N]: " INSTALL_PHP
    
    if [[ "$INSTALL_PHP" =~ ^[Yy]$ ]]; then
        echo "Installing PHP..."
        sudo apt update
        sudo apt install -y php php-mysql php-cli php-mbstring php-xml
        
        if command -v php &> /dev/null; then
            echo -e "${GREEN}✓ PHP installed successfully${NC}"
        else
            echo -e "${RED}✗ Installation failed${NC}"
            exit 1
        fi
    else
        echo ""
        echo "Please install PHP and run this script again."
        exit 1
    fi
else
    PHP_VERSION=$(php -v | head -n 1 | cut -d " " -f 2)
    echo -e "${GREEN}✓ Found PHP $PHP_VERSION${NC}"
fi

# Check for required PHP extensions
echo -n "Checking PHP extensions... "
MISSING_EXTS=""

php -m | grep -q "pdo_mysql" || MISSING_EXTS="$MISSING_EXTS pdo_mysql"
php -m | grep -q "json" || MISSING_EXTS="$MISSING_EXTS json"

if [ -z "$MISSING_EXTS" ]; then
    echo -e "${GREEN}✓ All required extensions found${NC}"
else
    echo -e "${YELLOW}⚠ Missing extensions:$MISSING_EXTS${NC}"
    echo "Install with: ${BLUE}sudo apt install php-mysql${NC}"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " MySQL/WAMP Database Connection"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Test MySQL connection
read -p "MySQL host [127.0.0.1]: " DB_HOST
DB_HOST=${DB_HOST:-127.0.0.1}

read -p "MySQL port [3306]: " DB_PORT
DB_PORT=${DB_PORT:-3306}

read -p "MySQL username [root]: " DB_USER
DB_USER=${DB_USER:-root}

read -sp "MySQL password: " DB_PASS
echo ""

echo -n "Testing MySQL connection... "
php -r "
try {
    \$conn = new PDO('mysql:host=$DB_HOST;port=$DB_PORT', '$DB_USER', '$DB_PASS');
    echo 'success';
} catch (Exception \$e) {
    echo 'failed: ' . \$e->getMessage();
    exit(1);
}
" 2>&1 | grep -q "success"

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Connected${NC}"
else
    echo -e "${RED}✗ Failed${NC}"
    echo ""
    echo "Please ensure:"
    echo "1. WAMP MySQL is running"
    echo "2. Credentials are correct"
    echo "3. MySQL is accessible on $DB_HOST:$DB_PORT"
    echo ""
    read -p "Continue anyway? [y/N]: " CONTINUE
    if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Update database configuration
echo -n "Updating database configuration... "
cat > config/database.php << EOF
<?php
/**
 * Database Configuration - Development Environment
 * Auto-generated by dev-setup.sh
 */

// Database credentials
define('DB_HOST', '$DB_HOST');
define('DB_PORT', '$DB_PORT');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');
define('DB_NAME', 'fmo_fisherfolk_management_system');
define('DB_CHARSET', 'utf8mb4');

/**
 * Get database connection
 * @return PDO Database connection object
 */
function getDBConnection() {
    static \$conn = null;
    
    if (\$conn === null) {
        try {
            \$dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=" . DB_CHARSET;
            \$options = [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ];
            
            \$conn = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
        } catch (PDOException \$e) {
            http_response_code(500);
            die(json_encode([
                'error' => 'Database connection failed',
                'message' => \$e->getMessage()
            ]));
        }
    }
    
    return \$conn;
}

/**
 * Execute a query and return results
 * @param string \$sql SQL query
 * @param array \$params Parameters for prepared statement
 * @return array Query results
 */
function executeQuery(\$sql, \$params = []) {
    try {
        \$conn = getDBConnection();
        \$stmt = \$conn->prepare(\$sql);
        \$stmt->execute(\$params);
        return \$stmt->fetchAll();
    } catch (PDOException \$e) {
        http_response_code(500);
        die(json_encode([
            'error' => 'Query execution failed',
            'message' => \$e->getMessage()
        ]));
    }
}

/**
 * Set JSON response headers
 */
function setJSONHeaders() {
    header('Content-Type: application/json');
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
}
EOF

echo -e "${GREEN}✓ Done${NC}"

# Check if database exists
echo -n "Checking for fmo_fisherfolk_management_system database... "
DB_EXISTS=$(php -r "
try {
    \$conn = new PDO('mysql:host=$DB_HOST;port=$DB_PORT', '$DB_USER', '$DB_PASS');
    \$stmt = \$conn->query('SHOW DATABASES LIKE \"fmo_fisherfolk_management_system\"');
    echo \$stmt->rowCount() > 0 ? 'yes' : 'no';
} catch (Exception \$e) {
    echo 'error';
}
" 2>&1)

if [ "$DB_EXISTS" == "yes" ]; then
    echo -e "${GREEN}✓ Found${NC}"
elif [ "$DB_EXISTS" == "no" ]; then
    echo -e "${YELLOW}⚠ Not found${NC}"
    echo ""
    read -p "Would you like to create the database and import sample data? [Y/n]: " CREATE_DB
    
    if [[ ! "$CREATE_DB" =~ ^[Nn]$ ]]; then
        echo "Creating database..."
        php -r "
        try {
            \$conn = new PDO('mysql:host=$DB_HOST;port=$DB_PORT', '$DB_USER', '$DB_PASS');
            \$conn->exec('CREATE DATABASE IF NOT EXISTS fmo_fisherfolk_management_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
            echo 'Database created\n';
        } catch (Exception \$e) {
            echo 'Error: ' . \$e->getMessage() . '\n';
            exit(1);
        }
        "
        
        echo "Importing schema..."
        php -r "
        \$conn = new PDO('mysql:host=$DB_HOST;port=$DB_PORT;dbname=fmo_fisherfolk_management_system', '$DB_USER', '$DB_PASS');
        \$sql = file_get_contents('sql/schema.sql');
        \$conn->exec(\$sql);
        echo 'Schema imported\n';
        "
        
        echo "Importing sample data..."
        php -r "
        \$conn = new PDO('mysql:host=$DB_HOST;port=$DB_PORT;dbname=fmo_fisherfolk_management_system', '$DB_USER', '$DB_PASS');
        \$sql = file_get_contents('sql/sample_data.sql');
        \$conn->exec(\$sql);
        echo 'Sample data imported\n';
        "
        
        echo -e "${GREEN}✓ Database setup complete${NC}"
    fi
else
    echo -e "${RED}✗ Could not check${NC}"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " Development Server Configuration"
echo "═══════════════════════════════════════════════════════════════"
echo ""

read -p "Server host [localhost]: " SERVER_HOST
SERVER_HOST=${SERVER_HOST:-localhost}

read -p "Server port [8080]: " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-8080}

# Create run script
cat > run-dev-server.sh << 'EOF'
#!/bin/bash

# Fisherfolk Dashboard - Development Server Runner

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

SERVER_HOST="localhost"
SERVER_PORT="8080"

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Fisherfolk Dashboard - Development Server                ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}🚀 Starting PHP development server...${NC}"
echo ""
echo -e "   📍 URL: ${YELLOW}http://$SERVER_HOST:$SERVER_PORT${NC}"
echo -e "   📂 Root: $(pwd)/public"
echo ""
echo -e "${GREEN}Press Ctrl+C to stop the server${NC}"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

cd public
php -S $SERVER_HOST:$SERVER_PORT ../dev-router.php
EOF

chmod +x run-dev-server.sh

# Update run script with user's preferences
sed -i "s/SERVER_HOST=\"localhost\"/SERVER_HOST=\"$SERVER_HOST\"/" run-dev-server.sh
sed -i "s/SERVER_PORT=\"8080\"/SERVER_PORT=\"$SERVER_PORT\"/" run-dev-server.sh

echo -e "${GREEN}✓ Development server configured${NC}"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " ${GREEN}✓ Setup Complete!${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "To start the development server:"
echo "  ${BLUE}./run-dev-server.sh${NC}"
echo ""
echo "Then open your browser to:"
echo "  ${YELLOW}http://$SERVER_HOST:$SERVER_PORT${NC}"
echo ""
echo "The server will use your WAMP MySQL database at:"
echo "  Host: $DB_HOST:$DB_PORT"
echo "  Database: fmo_fisherfolk_management_system"
echo ""
